### ISSUE TITLE
No module named 'Foundation' ?

### ISSUE THREAD

**Issue by seishonagon** [RhetTbull/osxmetadata#3]
Thanks for closing the last issue. Now when I try to install osxmetadata I get : 
```
Traceback (most recent call last):
  File "setup.py", line 15, in <module>
    from osxmetadata.version import __version__ as version
  File "/Users/paul/Downloads/osxmetadata-master/osxmetadata/__init__.py", line 13, in <module>
    from . import _applescript
  File "/Users/paul/Downloads/osxmetadata-master/osxmetadata/_applescript.py", line 17, in <module>
    from Foundation import (
ModuleNotFoundError: No module named 'Foundation'
```

I don't *think* my Python install is bad, but I'm not sure what to do?

**Comment by RhetTbull** [comment]
Weird...I’ll take a look and see if I can reproduce.  Try this before running setup.py and let me know if you get the same error:
pip install pyobjc

**Comment by RhetTbull** [comment]
I was able to reproduce the bug.  Problem was new code I had put in setup.py to automatically detect version number.  This triggered a problem if user did not already have xattr or pyobjc modules installed.  I've fixed setup.py in new version 0.96.87 on github

**Comment by seishonagon** [comment]
Thanks! Seems to work like a charm now.

**Comment by RhetTbull** [comment]
Great! Let me know if you any other issues.
