### ISSUE TITLE
Thanks a lot! Backed up metadata rich Mac folders before migrating to Linux NAS

### ISSUE THREAD

**Issue by porg** [RhetTbull/osxmetadata#55]
## 👍 Praise    and    ❤️ Thanks
- First got acquainted with **osxmetadata** when writing script [archive-order-to-metadata.sh](https://gist.github.com/porg/449ad9a61a75c113f771760b328ebe01) together with @gingerbeardman
- Today revisted **osxmetadata**.
  - Wanted to use it to build a backup/restore script from it.
  - But hurray! Instead of 2-8 hours of building a script, I discovered --backup and --restore are included already!
- Tested it on test folder. Works like a charm! Great! Thank you!
  - Used shell globbing to recursively save directories at different depth by calling it always with one more asterisk
    ```
    osxmetadata --backup ~/my/path/*
    osxmetadata --backup ~/my/path/*/*
    osxmetadata --backup ~/my/path/*/*/*
    ```
- Now will move all the folders & files to a Linux based NAS.
- And should things go bad regarding metadata, I have the metadata backed up, and will be able to restore it.

## Note: On subsequent runs --backup works additively with inexisting records, updates existing records, but does NOT remove files deleted meanwhile
Example:
- If ~/my/path/one/ has files Aaaron.txt Bravo.txt Berlin.jpg Charlotte.mp4
- Then `osxmetadata --backup ~/my/path/one/A*` creates an Aaaron.txt record in ~/my/path/one/.osxmetadata.json
- And `osxmetadata --backup ~/my/path/one/B*` adds records Bravo.txt Berlin.jpg in ~/my/path/one/.osxmetadata.json
- Change the tags and comment for Aaron.txt
- Run `osxmetadata --backup ~/my/path/one/A*` again updates the Aaaron.txt record in ~/my/path/one/.osxmetadata.json
- Delete file Charlotte.mp4
- Run `osxmetadata --backup ~/my/path/one/*` keeps the Charlotte.mp4 record in ~/my/path/one/.osxmetadata.json although Charlotte.mp4 was deleted meanwhile.

💡 I found this out by trial and error. 👉 Maybe you could add info about this behavior to the manual.

**Comment by RhetTbull** [comment]
Great -- glad you found osxmetadata useful.  

> 💡 I found this out by trial and error. 👉 Maybe you could add info about this behavior to the manual.

Yes, I should add a note in the docs about this behavior.  It is working as designed -- the backup database is very simple and does not remove any data from the .json database for any file that's been deleted from the directory.   I've thought about making a more robust database (perhaps using sqlite) but the current version works for my use case (syncing metadata across cloud backups that don't sync metadata).

**Comment by porg** [comment]
- Your use case is my use case (relying on Finder Tags + comments and storing on Linux NAS with some fear of metadata loss)
- I think keeping this in a dot prefixed JSON + storing filepath + filename is quite robust + portable. Suits me well!
- So I guess even in scenarios were the filepath changed (as folders above were moved/renamed) osxmetadata will be able to identify by filename.

---

- One could also store the inode as another means for identification.
  - On macOS any file can also be addressed by inode-URLs, read more at [EclecticLights](https://eclecticlight.co/2018/03/05/open-recent-inodes-and-bookmarks-how-macos-remembers-files/)
    - file:///.file/id=123.456 the most reliable, also works well if you want to refer to files in Calendar in the notes or URL field. Also the `open` command works fine with it.
    - file:///.vol/123/456 another way. Less supported. I.e. the `open` command in terminal does not work with it.
  - But then for NAS the way to get the inode would be different.

**Comment by RhetTbull** [comment]
> So I guess even in scenarios were the filepath changed (as folders above were moved/renamed) osxmetadata will be able to identify by filename.

Yes, this is an advantage of the current design.  While the JSON file stores the whole path to the file, a separate `.osxmetadata.json` file is created in each directory and only the file name is used to restore.  Thus, if you move files or rename a directory, the metadata can still be restored as long as the `.osxmetadata.json` file is present.

Using something like inode would break this and would also break my use case where I backup metadata on one computer, sync to the cloud, then restore metadata on a second computer.  In this case, the only thing that can be used for backup/restore is the file name as in my case, the full path on one computer is different than the full path on the second computer.

**Comment by RhetTbull** [comment]
Additionally, I should add that the backup/restore code is currently very simple (just a few lines of code) and what it does is merge the data for the current file with the existing backup. I'm reluctant to change this but might add a `--clean` option or something similar that, when used with `--backup`, will purge any deleted files from the backup.  Because of the way I use osxmetadata to sync two computers, this wouldn't be helpful for me as the files on each computer might be different depending on sync state.

**Comment by porg** [comment]
Also thing that this least aggressive behavior is safe.
But appreciate an explicit extra --clean flag.

**Comment by RhetTbull** [comment]
I've opened an new issue to add `--clean` and updated the README to explain how the backup file actually works.
