### ISSUE TITLE
Validators say osxmetadata.json is malformed JSON

### ISSUE THREAD

**Issue by porg** [RhetTbull/osxmetadata#57]
## Foreword
- osxmetadata correctly performs its --backup and --restore operations, so I do not mind too much.

## How I noticed
- But a the typical Mac user I quick look almost any file during work.
- So when using osxmetadata and asking myself things like "Has osxmetadata picked up that file?" or "Has it picked up that particular metadata attribute?" I tend to just do a quick quicklook.
- And here my QuickLook [plugin for JSON](https://jsononline.net/json-validator) tells me it's malformed.

## Other checks
- So does https://jsononline.net/json-validator
- At least Microsoft Visual Studio Code renders it correctly (if you would do a validation I assume it would should too).
<img width="1142" alt="osxmetadata JSON malformed" src="https://user-images.githubusercontent.com/737143/179115674-818fc673-34fa-4ffb-9920-e63712323bff.png">

## Followup
- If you decide too fix this indeed
- Please make sure later versions can convert old malformed JSONs, and fix them when encountering them
- Maybe also offer a batch script like `find /Volumes/yourVolume/ -name ".osxmetadata.json" -exec "<do the fixing/corrections>"`

**Comment by RhetTbull** [comment]
Thanks for the detailed report. The basic problem is that technically JSON expects an array of values (enclosed in square brackets) when there is more than one record but osxmetadata writes each file record as a separate JSON record per line without the syntax of a JSON array. Each record (line) is valid JSON but not the whole file. I could change this easily but detecting the old style vs the new style would be difficult. The format was designed to be very simple and works fine for osxmetadata. I'll have to think on this to decide if it's worth changing.

**Comment by RhetTbull** [comment]
I decided it was better to have well-formed JSON than to keep the existing format so [v0.99.38](https://github.com/RhetTbull/osxmetadata/releases/tag/v0.99.38) will silently upgrade any `.osxmetadata.json` file it accesses with --backup to be well-formed JSON.  This breaks backwards compatibility so once you upgrade you cannot use an old version of osxmetadata to backup or restore.

**Comment by RhetTbull** [comment]
@all-contributors please add @porg for bug

**Comment by porg** [comment]
👍 Thanks for the credits! 😉

**Comment by porg** [comment]
Today via pipx I upgraded osxmetadata to v1.0.0 and it created a wellformed JSON which my [QuickLookJSON](http://www.sagtau.com/quicklookjson.html) shows just nicely.

**Comment by RhetTbull** [comment]
@porg Great! Glad it's working well now.
